### PR TITLE
Present the Codecov test coverage badge in the readme

### PR DESCRIPTION
**Pull request by jstasiak**
Good to see at a glance how good (or bad!) our coverage is.

### CODE REVIEW

**Comment by jstasiak** [comment]
Note that until https://github.com/lune-climate/lune-shipping-csv-tool/pull/64 is merged the coverage is 0% 🙃

**Comment by stoich** [comment]
no idea what this is

**Review by stoich — APPROVED** [review]

**Comment by jstasiak** [comment]
It shows this thing: [Coverage](https://codecov.io/github/lune-climate/lune-shipping-csv-tool) and it links to the master branch coverage/file browser in Codecov so you can see what's covered and what's not

**Comment by jstasiak** [comment]
Preview: https://github.com/lune-climate/lune-shipping-csv-tool/blob/coverage-badge/README.md

**Pull request merged**
